Account Validation Implementation
openMF/ph-ee-id-account-validator-impl pull request #1
Opened 2023-05-05 08:20 UTC by apurbraj

2023-05-24 13:09 UTC, fynmanoj requested changes

2023-05-24 13:09 UTC, fynmanoj commented on README.md
> +account validator implementations for PHEE Id mapper. This repo contains the implemntation for gsma and mojaloop account validation which will be used as a dependency in  Identity Account Mapper.
please add the notes on how to build the Jar and use them

2023-05-24 13:09 UTC, fynmanoj commented on settings.gradle
> +rootProject.name = 'ph-ee-id-maapper-account-validator-impl'
the repo name is updated. please update it here as well

2023-05-24 13:09 UTC, fynmanoj commented on src/main/java/org/mifos/pheeidmaapperaccountvalidatorimpl/mojaloopconnector/MojaloopAccountValidation.java
> +        return null;
why this method is returning null while the type is Boolean?

2023-05-24 13:09 UTC, fynmanoj commented on src/main/resources/application.properties
remove empty file

2023-05-25 11:31 UTC, apurbraj commented on src/main/java/org/mifos/pheeidmaapperaccountvalidatorimpl/mojaloopconnector/MojaloopAccountValidation.java
> +        return null;
The AccountValidationService class is implemented for both Mojaloop and GSMA. The signature of the validateAccount method is the same for both implementations, but the result of the validation is different. For GSMA, the result is returned immediately, but for Mojaloop, the result is returned asynchronously.

2023-05-30 06:06 UTC, fynmanoj approved these changes

2023-05-30 06:07 UTC, merged